spring:
  application:
    name: backend
  datasource:
    url: jdbc:mariadb://localhost:3306/whiteboard
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
  security:
    user:
      name: admin
      password: admin

mybatis:
  mapper-locations: classpath:mappers/*.xml # SQL ??? ?? ??(.xml) ??
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: kr.co.chunjae.backend.dto # dto ??? ??? ??? ??? resultType? ???? ?? ??